### ISSUE TITLE
error: Package ‘ido-ubiquitous-’ is unavailable

### ISSUE THREAD

**Issue by justnull** [sicper/emacs-for-clojure#1]
Warning (initialization): An error occurred while loading ‘c:/Users/*/AppData/Roaming/.emacs.d/init.el’:

error: Package ‘ido-ubiquitous-’ is unavailable

**Comment by jueqingsizhe66** [comment]
Try `M-x package-install ido-ubiquitous`.  Something missing for the package ido

**Comment by jueqingsizhe66** [comment]
The emacs config will initially install some packages for the emacs program. If network connection is missing or Emacs package-archives cannot find the package,  some error may occur.

So , 
  1. try again , or manual install some plugins
  2.  you can add more package-archive at the beginning of the init.el
```
(setq package-archives '(("gnu"   . "http://elpa.emacs-china.org/gnu/")
                         ("melpa-stable" . "http://elpa.emacs-china.org/melpa-stable/")
                         ("melpa" . "http://elpa.emacs-china.org/melpa/")
                         ("marmalada" . "http://elpa.emacs-china.org/marmalade/")))
```

**Comment by jueqingsizhe66** [comment]
When you bump into something initial error, you can use `emacs --debug-init` to see the detailed error info which do good for your correction.

**Comment by jiacai2050** [comment]
@justnull Any luck?

**Comment by justnull** [comment]
![clipboard](https://user-images.githubusercontent.com/724861/44642707-0f680f80-aa00-11e8-84a1-89440d431fbd.png)
it still can not found ido-ubiquitous after I add package-archives site.
I don't know how to use --debug-init on windows 10.

**Comment by jiacai2050** [comment]
After update package-archives, M-x `package-refresh-contents` to refresh local package list.
